#!/bin/bash

set -euf -o pipefail
set -x

bump() {
  LIVECHECK=$(brew livecheck "$1" --json)
  echo "$LIVECHECK" | jq

  OUTDATED=$(echo "$LIVECHECK" | jq --raw-output '.[0].version.outdated')
  if [[ "$OUTDATED" == "false" ]]; then
    return 0
  fi

  LATEST_VERSION=$(echo "$LIVECHECK" | jq --raw-output '.[0].version.latest')

  brew bump-formula-pr --verbose --write --commit --no-audit "$1" --version "$LATEST_VERSION"
}

bump ./csv2json.rb
bump ./displayrcd.rb
bump ./icloud-backup-utils.rb
