name: Homebrew Livecheck

on:
  schedule:
    - cron: "0 9 * * *"

  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Homebrew
        run: brew update || true

      - name: Install tap
        run: brew tap josh/tap

      - name: Update outdated formulas
        run: script/bump-outdated-formula

      - name: Commit formula changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add *.rb
          git commit --message "Update formulas" || true

      - name: Push changes
        run: git push
