name: Homebrew

on: [push]

jobs:
  audit:
    runs-on: ubuntu-24.04

    env:
      HOMEBREW_DEVELOPER: "1"

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@841d750a0ed9262d3c3ca31f2173974696bc261a # master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems --groups=audit,style

      - name: Install brew style dependencies
        run: |
          brew install actionlint shellcheck

      - name: Style
        run: |
          brew style josh/tap

      - name: Audit formulas
        run: |
          brew audit --strict --online --tap josh/tap
