name: Homebrew Livecheck

on:
  schedule:
    - cron: "0 9 * * *"

  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-latest

    steps:
      - name: Update Homebrew
        run: brew update || true

      - name: Check out tap
        uses: actions/checkout@v2
        with:
          path: "/usr/local/Homebrew/Library/Taps/josh/homebrew-tap"

      - name: Update outdated formulas
        working-directory: "/usr/local/Homebrew/Library/Taps/josh/homebrew-tap"
        run: script/bump-outdated-formula

      - name: Commit formula changes
        working-directory: "/usr/local/Homebrew/Library/Taps/josh/homebrew-tap"
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'joshbot@users.noreply.github.com'
          git add *.rb
          git commit --message "Update formulas" || true

      - name: Push changes
        working-directory: "/usr/local/Homebrew/Library/Taps/josh/homebrew-tap"
        run: git push
